lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: "LHCb Milano computing"
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
search_enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "LHCb-MI-Computing on GitHub":
    - "//github.com/LHCb-Milano/LHCb-MI-Computing"
logo: "images/lhcb.png"